export const GUEST_SUCCESS = 'GUEST_SUCCESS';
export const GUEST_ERROR = 'GUEST_ERROR';
export const GUEST_ENTERED_EVENT_SUCCESS = 'GUEST_ENTERED_EVENT_SUCESS';
export const GUEST_ENTERED_EVENT_ERROR = 'GUEST_ENTERED_EVENT_ERROR';
export const UPDATE_LEAVE_SUCCESS = 'UPDATE_LEAVE_SUCCESS';
export const UPDATE_LEAVE_ERROR = 'UPDATE_LEAVE_ERROR';
